export const CHANGE_SELECTED_SUBJECT = "CHANGE_SELECTED_SUBJECT";
export const COURSES_LOADED 		 = "COURSES_LOADED";
export const CHANGE_SELECTED_COURSE  = "CHANGE_SELECTED_COURSE";
export const GENERATE_SCHEDULE		 = "GENERATE_SCHEDULE";
export const DELETE_COURSE			 = "DELETE_COURSE";
export const GET_COURSES_FROM_OFFSET = "GET_COURSES_FROM_OFFSET";